# Generated by Django 3.1.5 on 2021-01-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_author2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='author2',
            name='date_of_death',
        ),
        migrations.AddField(
            model_name='author',
            name='favorite',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
