# Generated by Django 3.1.5 on 2021-01-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210112_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='favorite',
            field=models.CharField(default='', max_length=100),
        ),
    ]
