# Generated by Django 3.1.5 on 2021-01-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210112_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='favorite',
            field=models.CharField(default='you need to type something', max_length=100),
        ),
    ]
