# Generated by Django 3.1.5 on 2021-01-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210112_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='favorite',
            new_name='favoriteeeee',
        ),
    ]
