# Generated by Django 3.1.5 on 2021-01-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210112_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Education',
            field=models.CharField(default='you need to type something', max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='intrest',
            field=models.CharField(default='you need to type something', max_length=100),
        ),
    ]
