# Generated by Django 3.1.5 on 2021-01-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210112_1242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author2',
            new_name='Jackson',
        ),
    ]
